model:
    encoders:
      camera:
        vtransform:
          depth_loss: 'smoothl1loss'
          raw_image_size: [1024, 1224]
  
reserve_single_sweep: true

lr_config:
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 1.0e-3