point_cloud_range: [0, -25.6, -5.0, 51.2, 25.6, 3.0]
voxel_size: [0.1, 0.1, 0.2]
grid_size: [512, 512, 41]
post_center_limit_range: [-10, -35.6, -10.0, 61.2, 35.6, 10.0]
reserve_single_sweep: true


model:
  encoders:
    camera:
      vtransform:
        dbound: [1.0, 60.0, 0.5]
        depth_loss: 'smoothl1loss'
        raw_image_size: [1208, 1920]

lr_config:
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 1.0e-3