depth_reduction_op: mean
depth_reduction: max


model:
  depth_condition:
    backbone:
      norm_cfg:
        requires_grad: true
      style: pytorch
      with_cp: true
      init_cfg:
        type: Pretrained
        checkpoint: open-mmlab://resnet18_v1c