seed: 0
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 1

log_config:
  interval: 50
  hooks:
    -
      type: TextLoggerHook
    -
      type: TensorboardLoggerHook

load_from: null
resume_from: null

cudnn_benchmark: false
fp16:
  loss_scale:
    growth_interval: 2000

max_epochs: 20
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}

# lr_config:
#   policy: cyclic
#   target_ratio: [10, 0.0001]
#   cyclic_times: 1
#   step_ratio_up: 0.4

# momentum_config:
#     policy: 'cyclic'
#     target_ratio: [0.8947368421052632, 1]
#     cyclic_times: 1
#     step_ratio_up: 0.4